name: Build and push image

on:
  release:
    types: [created]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "oc4ids-datastore-api"
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Print version
        run: echo $VERSION
      - name: Build and push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo $IMAGE_ID
          docker build . -t ${IMAGE_ID}:${VERSION} -t ${IMAGE_ID}:latest
          docker push --all-tags ${IMAGE_ID}
