name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dev requirements
        run: pip install -r requirements_dev.txt
      - name: Install local package
        run: pip install .
      - name: Check black
        run: black --check oc4ids_datastore_api/ tests/
      - name: Check isort
        run: isort --check-only oc4ids_datastore_api/ tests/
      - name: Check flake8
        run: flake8 oc4ids_datastore_api/ tests/
      - name: Check mypy
        run: mypy oc4ids_datastore_api/ tests/
      - name: Run tests
        run: pytest
